---

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.18.0
    - DOCKER_HUB_REPO=thomasjpfan/ansible-docker-runner
  matrix:
    - PY_VERSION=2
    - PY_VERSION=3

addons:
  apt:
    packages:
      - docker-ce=18.01.0~ce-0~ubuntu

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f tests/docker-compose.yml up -d

script:
  - docker image build -t $DOCKER_HUB_REPO:$TRAVIS_BRANCH -f python$PY_VERSION/Dockerfile .
  - >
    docker run --rm -v $PWD:/etc/ansible/roles/role_to_test \
      -v /var/run/docker.sock:/var/run/docker.sock:ro -ti \
      $DOCKER_HUB_REPO:$TRAVIS_BRANCH cli all

after_script:
  - docker-compose -f tests/docker-compose.yml down

after_success:
  - >
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        docker_file="python${PY_VERSION}/Dockerfile"
        docker_v=$(grep "FROM docker" $docker_file | cut -d ':' -f2)
        ansible_v=$(grep "ENV ANSIBLE_VERSION" $docker_file | awk '{{ print $3 }}')
        lint_v=$(grep "ENV ANSIBLE_LINT_VERSION" $docker_file | awk '{{ print $3 }}')
        testinfra_v=$(grep "ENV TESTINFRA_VERSION" $docker_file | awk '{{ print $3 }}')
        tag="docker-${docker_v}-py${PY_VERSION}-ansible-${ansible_v}-lint-${lint_v}-testinfra-${testinfra_v}"
        docker tag $DOCKER_HUB_REPO:$TRAVIS_BRANCH $DOCKER_HUB_REPO:$tag
        docker push $DOCKER_HUB_REPO:$tag
        if [ "$PY_VERSION" == "2" ]; then
          docker tag $DOCKER_HUB_REPO:$TRAVIS_BRANCH $DOCKER_HUB_REPO:latest
          ddocker push $DOCKER_HUB_REPO:latest
        fi
      fi
    fi